SecRule REQUEST_BODY|ARGS|ARGS_NAMES|REQUEST_URI|REQUEST_HEADERS     "@rx (?i)(\\)?['\"]\s*OR\s*1=1\s*--"     "id:1005,    phase:2,    deny,    status:403,    msg:'Custom SQLi Rule',    chain"
    SecRule REQUEST_HEADERS:Content-Type "application/json"
